project/config/routes.rb
Rails.application.routes.draw do
  resources :scaffoldings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    root "projects#index"
    resources :projects
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

project/app/models/scaffolding.rb
class Scaffolding < ApplicationRecord
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project/app/controllers/scaffoldings_controller.rb
class ScaffoldingsController < ApplicationController
  before_action :set_scaffolding, only: %i[ show edit update destroy ]

  # GET /scaffoldings or /scaffoldings.json
  def index
    @scaffoldings = Scaffolding.all
  end

  # GET /scaffoldings/1 or /scaffoldings/1.json
  def show
  end

  # GET /scaffoldings/new
  def new
    @scaffolding = Scaffolding.new
  end

  # GET /scaffoldings/1/edit
  def edit
  end

  # POST /scaffoldings or /scaffoldings.json
  def create
    @scaffolding = Scaffolding.new(scaffolding_params)

    respond_to do |format|
      if @scaffolding.save
        format.html { redirect_to scaffolding_url(@scaffolding), notice: "Scaffolding was successfully created." }
        format.json { render :show, status: :created, location: @scaffolding }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scaffolding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scaffoldings/1 or /scaffoldings/1.json
  def update
    respond_to do |format|
      if @scaffolding.update(scaffolding_params)
        format.html { redirect_to scaffolding_url(@scaffolding), notice: "Scaffolding was successfully updated." }
        format.json { render :show, status: :ok, location: @scaffolding }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scaffolding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scaffoldings/1 or /scaffoldings/1.json
  def destroy
    @scaffolding.destroy

    respond_to do |format|
      format.html { redirect_to scaffoldings_url, notice: "Scaffolding was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scaffolding
      @scaffolding = Scaffolding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scaffolding_params
      params.require(:scaffolding).permit(:title, :description)
    end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/scaffoldings_helper.rb
module ScaffoldingsHelper
end

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

project/app/views/scaffoldings/_form.html.erb
<%= form_with(model: scaffolding) do |form| %>
  <% if scaffolding.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(scaffolding.errors.count, "error") %> prohibited this scaffolding from being saved:</h2>

      <ul>
        <% scaffolding.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project/app/views/scaffoldings/_scaffolding.html.erb
<div id="<%= dom_id scaffolding %>">
  <p>
    <strong>Title:</strong>
    <%= scaffolding.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= scaffolding.description %>
  </p>

</div>

project/app/views/scaffoldings/edit.html.erb
<h1>Editing scaffolding</h1>

<%= render "form", scaffolding: @scaffolding %>

<br>

<div>
  <%= link_to "Show this scaffolding", @scaffolding %> |
  <%= link_to "Back to scaffoldings", scaffoldings_path %>
</div>

project/app/views/scaffoldings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scaffoldings</h1>

<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<div id="scaffoldings">
  <% @scaffoldings.each do |scaffolding| %>
    <%= render scaffolding %>
    <p>
      <%= link_to "Show this scaffolding", scaffolding %>
    </p>
  <% end %>
</div>

<%= link_to "New scaffolding", new_scaffolding_path %>

project/app/views/scaffoldings/new.html.erb
<h1>New scaffolding</h1>

<%= render "form", scaffolding: @scaffolding %>

<br>

<div>
  <%= link_to "Back to scaffoldings", scaffoldings_path %>
</div>

project/app/views/scaffoldings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @scaffolding %>

<div>
  <%= link_to "Edit this scaffolding", edit_scaffolding_path(@scaffolding) %> |
  <%= link_to "Back to scaffoldings", scaffoldings_path %>

  <%= button_to "Destroy this scaffolding", @scaffolding, method: :delete %>
</div>